name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Dockerfile'
      - 'build.gradle'
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - 'settings.gradle'
      - 'src/**'
      - '.github/workflows/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build & publish the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/frc5183/beeapi:latest
        docker push ghcr.io/frc5183/beeapi:latest
    
